// <auto-generated />
using System;
using EntityFrameworkCoreLab.Persistence.EntityFrameworkContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EntityFrameworkCoreLab.Persistence.Migrations.Amazon
{
    [DbContext(typeof(AmazonCodeFirstDbContext))]
    [Migration("20200303104422_CreateDTODataType")]
    partial class CreateDTODataType
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EntityFrameworkCoreLab.Persistence.DataTransferObjects.Amazon.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("date");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("nvarchar(11)")
                        .HasMaxLength(11);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(80)")
                        .HasMaxLength(80);

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("EntityFrameworkCoreLab.Persistence.DataTransferObjects.Amazon.DTODataType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("ArrayBytesProperty")
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("BoolProperty")
                        .HasColumnType("bit");

                    b.Property<bool?>("BoolPropertyNullable")
                        .HasColumnType("bit");

                    b.Property<string>("CharProperty")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("CharPropertyNullable")
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime>("DateProperty")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DatePropertyNullable")
                        .HasColumnType("date");

                    b.Property<DateTime>("DateTimeProperty")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateTimePropertyNullable")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DecimalLowerPrecisionProperty")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<decimal>("DecimalProperty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DecimalPropertyNullable")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("DoubleProperty")
                        .HasColumnType("float");

                    b.Property<double?>("DoublePropertyNullable")
                        .HasColumnType("float");

                    b.Property<float>("FloatProperty")
                        .HasColumnType("real");

                    b.Property<float?>("FloatPropertyNullable")
                        .HasColumnType("real");

                    b.Property<int>("IntProperty")
                        .HasColumnType("int");

                    b.Property<int?>("IntPropertyNullable")
                        .HasColumnType("int");

                    b.Property<long>("LongProperty")
                        .HasColumnType("bigint");

                    b.Property<long?>("LongPropertyNullable")
                        .HasColumnType("bigint");

                    b.Property<string>("StringPropertyLimitedLength")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("StringPropertyMaxLength")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StringPropertyRequired")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("TimeSpanProperty")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("TimeSpanPropertyNullable")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("DTODataType");
                });
#pragma warning restore 612, 618
        }
    }
}
